var RestaurantsListData = [

    {   index: 1,
        price: 1200,
        view: 200,
        point: 9.1,
        title: "Karavalli",
        time: "1h 45m",
        publishedYear: 2021,
        category: "South Indian",
        location: "Bengaluru, Karnataka",
        imgUrl: "restaurant_1.jpg",
        desc: "Experience authentic South Indian coastal cuisine with rich flavors and fresh spices.",
    },

    {   index: 2,
        price: 950,
        view: 320,
        point: 8.9,
        title: "Bukhara",
        time: "2h 10m",
        publishedYear: 2015,
        category: "North Indian",
        location: "Delhi",
        imgUrl: "restaurant_2.jpg",
        desc: "Known for its robust flavors and signature tandoori dishes, a true North Indian experience.",
    },

    {   index: 3,
        price: 700,
        view: 180,
        point: 8.5,
        title: "Peter Cat",
        time: "1h 30m",
        publishedYear: 1995,
        category: "Anglo-Indian",
        location: "Kolkata, West Bengal",
        imgUrl: "restaurant_3.jpg",
        desc: "Specializes in iconic Chelo Kebabs and Anglo-Indian delicacies.",
    },

    {   index: 4,
        price: 650,
        view: 250,
        point: 7.8,
        title: "Annalakshmi",
        time: "1h 15m",
        category: "Vegetarian",
        publishedYear: 2019,
        location: "Chennai, Tamil Nadu",
        imgUrl: "restaurant_4.jpg",
        desc: "Offers a traditional South Indian vegetarian buffet served with a warm, homely ambiance.",
    },

    {   index: 5,
        price: 1400,
        view: 140,
        point: 9.3,
        title: "Peshawri",
        time: "2h 05m",
        category: "Mughlai",
        publishedYear: 2022,
        location: "Mumbai, Maharashtra",
        imgUrl: "restaurant_5.jpg",
        desc: "Serves authentic Mughlai cuisine, renowned for its kebabs and creamy dal makhani.",
    },

    {   index: 6,
        price: 500,
        view: 120,
        point: 7.4,
        title: "Saravana Bhavan",
        time: "1h 00m",
        category: "South Indian",
        publishedYear: 1981,
        location: "Various Cities",
        imgUrl: "restaurant_6.jpg",
        desc: "Known for traditional South Indian meals, especially dosas and idlis.",
    },

    {   index: 7,
        price: 400,
        view: 270,
        point: 8.7,
        title: "Blue Tokai Coffee Roasters",
        time: "1h 20m",
        category: "Coffee Bar",
        publishedYear: 2017,
        location: "Mumbai, Maharashtra",
        imgUrl: "coffee_bars_1.jpg",
        desc: "Artisanal coffee with ethically sourced beans and cozy vibes for coffee lovers.",
    },

    {   index: 8,
        price: 300,
        view: 220,
        point: 8.5,
        title: "Third Wave Coffee Roasters",
        time: "1h 05m",
        category: "Coffee Bar",
        publishedYear: 2018,
        location: "Bengaluru, Karnataka",
        imgUrl: "coffee_bars_2.jpg",
        desc: "Popular for its specialty coffee, this place offers a unique and relaxed coffee experience.",
    },

    {   index: 9,
        price: 250,
        view: 180,
        point: 8.2,
        title: "Di Bella Coffee",
        time: "1h 10m",
        category: "Coffee Bar",
        publishedYear: 2016,
        location: "Mumbai, Maharashtra",
        imgUrl: "coffee_bars_3.jpg",
        desc: "Known for its unique brews and the famous gold-plated cappuccino experience.",
    },

    {   index: 10,
        price: 600,
        view: 310,
        point: 9.0,
        title: "Kuremal Mohan Lal Kulfi Wale",
        category: "Desserts",
        publishedYear: 1906,
        location: "Delhi",
        imgUrl: "bars_1.jpg",
        desc: "A historic kulfi shop serving over a century-old recipes with unique flavors.",
    },

    {   index: 11,
        price: 500,
        view: 230,
        point: 8.8,
        title: "Naturals Ice Cream",
        category: "Desserts",
        publishedYear: 1984,
        location: "Mumbai, Maharashtra",
        imgUrl: "bars_2.jpg",
        desc: "Known for its fresh, natural ingredients, offering unique flavors like tender coconut.",
    },

    {   index: 12,
        price: 350,
        view: 200,
        point: 8.6,
        title: "Haldiram's Sweets",
        category: "Desserts",
        publishedYear: 1980,
        location: "Nagpur, Maharashtra",
        imgUrl: "bars_3.jpg",
        desc: "Famous for traditional Indian sweets like rasgulla, gulab jamun, and an array of snacks.",
    },
];